os-probe: Add command
Probing the OS is an interesting thing to do on its own.  Provide a
separate command for that.  It also helps debug the script, so we can
remove some debugging code.

Signed-off-by: Alejandro Colomar <alx@nginx.com>

diff --git a/bin/setup-unit b/bin/setup-unit
--- a/bin/setup-unit
+++ b/bin/setup-unit
@@ -82,6 +82,9 @@ help_more_unit()
     echo '              Insert a JSON element read from standard input into a JSON';
     echo '              array read from a file at a given INDEX.';
     echo;
+    echo '      os-probe';
+    echo '              This script probes the OS, and prints details about the version.';
+    echo;
     echo '      ps      List unitd(8) processes.';
     echo;
     echo '      repo-config';
@@ -800,6 +803,78 @@ unit_json_ins()
 }
 
 
+unit_os_probe()
+{
+    help_unit_os_probe()
+    {
+        echo 'SYNOPSIS';
+        echo "      $program_name os-probe [-h]";
+        echo;
+        echo 'DESCRIPTION';
+        echo '      This script probes the OS, and prints details about the version.';
+        echo "      It prints three fields, delimited by ':'; the first is the OS,";
+        echo '      the second is the OS name, and the third is the OS version.';
+        echo;
+        echo 'OPTIONS';
+        echo '      -h, --help';
+        echo '              Print this help.';
+    }
+
+    while test -v 1; do
+        case "$1" in
+        -h | --help)
+            help_unit_os_probe;
+            exit 0;
+            ;;
+        -*)
+            >&2 help_unit_os_probe;
+            exit 1;
+            ;;
+        *)
+            break;
+            ;;
+        esac;
+        shift;
+    done;
+
+    os=$(uname | tr '[:upper:]' '[:lower:]')
+
+    if [ "$os" != 'linux' ] && [ "$os" != 'freebsd' ]; then
+        err "The OS isn't Linux or FreeBSD, can't proceed."
+    fi
+
+    if [ "$os" = 'linux' ]; then
+        osRelease='/etc/os-release';
+
+        if [ -f "$osRelease" ]; then
+            # The value for the ID and VERSION_ID may or may not be in quotes
+            osName=$(grep "^ID=" "$osRelease" | sed s/\"//g | awk -F= '{ print $2 }')
+            osVersion=$(grep '^VERSION_ID=' "$osRelease" | sed s/\"//g | awk -F= '{ print $2 }')
+        else
+            # rhel or centos 6.*
+            if rpm -q redhat-release-server >/dev/null 2>&1; then
+                osName=rhel
+                osVersion=$(rpm -q redhat-release-server |sed 's/.*-//' | awk -F. '{print $1"."$2;}')
+            elif rpm -q centos-release >/dev/null 2>&1; then
+                osName=centos
+                osVersion=$(rpm -q centos-release | sed 's/centos-release-//' | sed 's/\..*//' | awk -F- '{print $1"."$2;}')
+            else
+                err "Unable to determine OS and version, or the OS isn't supported"
+            fi
+        fi
+    else
+        osName=$os
+        osVersion=$(uname -rs | awk -F '[ -]' '{print $2}')
+        if [ -z "$osVersion" ]; then
+            err 'Unable to get the FreeBSD version'
+        fi
+    fi
+
+    osName=$(echo "$osName" | tr '[:upper:]' '[:lower:]')
+    echo "$os:$osName:$osVersion"
+}
+
+
 unit_ps()
 {
     help_unit_ps()
@@ -888,67 +963,6 @@ unit_repo_config()
         echo '              of actually running them.  Each command is';
         echo '              preceded by a line explaining what it does.';
     }
-
-    #####################################################################
-    # Function getOS
-    #
-    # Getting the OS is not the same on all distributions.  First, we use
-    # uname to find out if we are running on Linux or FreeBSD. For all the
-    # supported versions of Debian and Ubuntu, we expect to find the
-    # /etc/os-release file which has multiple lines with name-value pairs
-    # from which we can get the OS name and version. For Red Hat and its
-    # variants, the os-release file may or may not exist, depending on the
-    # version.  If it doesn't, then we look for the release package and
-    # get the OS and version from the package name. For FreeBSD, we use the
-    # "uname -rs" command.
-    #
-    # A string is written to stdout with three values separated by ":":
-    #    OS
-    #    OS Name
-    #    OS Version
-    #####################################################################
-    getOS ()
-    {
-        os=$(uname | tr '[:upper:]' '[:lower:]')
-
-        if [ "$os" != 'linux' ] && [ "$os" != 'freebsd' ]; then
-            warn "The OS isn't Linux or FreeBSD, can't proceed."
-            err  "On macOS, try 'brew install nginx/unit/unit'."
-        fi
-
-        if [ "$os" = 'linux' ]; then
-            osRelease='/etc/os-release';
-
-            if [ -f "$osRelease" ]; then
-                # The value for the ID and VERSION_ID may or may not be in quotes
-                osName=$( grep "^ID=" "$osRelease" | sed s/\"//g | awk -F= '{ print $2 }')
-                osVersion=$(grep '^VERSION_ID=' "$osRelease" | sed s/\"//g | awk -F= '{ print $2 }')
-            else
-                # rhel or centos 6.*
-                if rpm -q redhat-release-server >/dev/null 2>&1; then
-                    osName=rhel
-                    osVersion=$(rpm -q redhat-release-server |sed 's/.*-//' | awk -F. '{print $1"."$2;}')
-                elif rpm -q centos-release >/dev/null 2>&1; then
-                    osName=centos
-                    osVersion=$(rpm -q centos-release | sed 's/centos-release-//' | sed 's/\..*//' | awk -F- '{print $1"."$2;}')
-                else
-                    err "Unable to determine OS and version, or the OS isn't supported"
-                fi
-            fi
-        else
-            osName=$os
-            osVersion=$(uname -rs | awk -F '[ -]' '{print $2}')
-            if [ -z "$osVersion" ]; then
-                err 'Unable to get the FreeBSD version'
-            fi
-        fi
-
-        # Force osName to lowercase
-        osName=$(echo "$osName" | tr '[:upper:]' '[:lower:]')
-        echoDebug "getOS: os=$os osName=$osName osVersion=$osVersion"
-        echo "$os:$osName:$osVersion"
-    }
-
 
     installDebian ()
     {
@@ -1049,15 +1063,6 @@ __EOF__';
         dry_run_eval 'dnf makecache;';
     }
 
-    echoDebug ()
-    {
-        if [ "$debug" -eq 1 ]; then
-            echo "$@" 1>&2;
-        fi
-    }
-
-    debug=0 # If set to 1, debug message will be displayed
-
     while test -v 1; do
         case "$1" in
         -h | --help)
@@ -1087,7 +1092,7 @@ __EOF__';
 
     echo 'This script sets up the NGINX Unit repository';
 
-    osNameVersion=$(getOS)
+    osNameVersion=$(unit_os_probe || warn "On macOS, try 'brew install nginx/unit/unit'.")
     os=$(echo "$osNameVersion" | awk -F: '{print $1}')
     osName=$(echo "$osNameVersion" | awk -F: '{print $2}')
     osVersion=$(echo "$osNameVersion" | awk -F: '{print $3}')
@@ -1168,6 +1173,10 @@ freeport)
 json-ins)
     shift;
     unit_json_ins $@;
+    ;;
+os-probe)
+    shift;
+    unit_os_probe $@;
     ;;
 ps)
     shift;
