setup-unit: Simplify; no-op
Signed-off-by: Alejandro Colomar <alx@nginx.com>

diff --git a/bin/setup-unit b/bin/setup-unit
--- a/bin/setup-unit
+++ b/bin/setup-unit
@@ -87,10 +87,6 @@ repo_config()
     #####################################################################
     getOS ()
     {
-        os=""
-        osName=""
-        osVersion=""
-
         LC_ALL=C
 
         os=$(uname | tr '[:upper:]' '[:lower:]')
@@ -101,6 +97,8 @@ repo_config()
         fi
 
         if [ "$os" = "linux" ]; then
+            osRelease="/etc/os-release";
+
             if [ -f "$osRelease" ]; then
                 # The value for the ID and VERSION_ID may or may not be in quotes
                 osName=$( grep "^ID=" "$osRelease" | sed s/\"//g | awk -F= '{ print $2 }')
@@ -129,8 +127,6 @@ repo_config()
         osName=$(echo "$osName" | tr '[:upper:]' '[:lower:]')
         echoDebug "getOS: os=$os osName=$osName osVersion=$osVersion"
         echo "$os:$osName:$osVersion"
-
-        return 0
     }
 
 
@@ -146,8 +142,6 @@ repo_config()
         printf "deb-src [signed-by=/usr/share/keyrings/nginx-keyring.gpg] https://packages.nginx.org/unit/debian/ %s unit\n" "$(lsb_release -cs)" | tee -a /etc/apt/sources.list.d/unit.list
 
         apt update
-
-        return 0
     }
 
     installUbuntu ()
@@ -162,8 +156,6 @@ repo_config()
         printf "deb-src [signed-by=/usr/share/keyrings/nginx-keyring.gpg] https://packages.nginx.org/unit/ubuntu/ %s unit\n" "$(lsb_release -cs)" | tee -a /etc/apt/sources.list.d/unit.list
 
         apt update
-
-        return 0
     }
 
     installRedHat ()
@@ -188,8 +180,6 @@ __EOF__
         esac
 
         yum makecache
-
-        return 0
     }
 
     installAmazon ()
@@ -219,8 +209,6 @@ __EOF__
         esac
 
         yum makecache
-
-        return 0
     }
 
     installFedora ()
@@ -237,8 +225,6 @@ enabled=1
 __EOF__
 
         dnf makecache
-
-        return 0
     }
 
     echoDebug ()
@@ -248,72 +234,56 @@ __EOF__
         fi
     }
 
-    main()
-    {
-        debug=0 # If set to 1, debug message will be displayed
+    debug=0 # If set to 1, debug message will be displayed
 
-        test command -v curl >/dev/null 2>&1
-        || err "Error: curl not found in PATH.  It must be installed to run this script."
+    test command -v curl >/dev/null 2>&1
+    || err "Error: curl not found in PATH.  It must be installed to run this script."
 
-        test command -v awk > /dev/null 2>&1
-        || err "Error: awk not found in PATH.  It must be installed to run this script."
+    test command -v awk > /dev/null 2>&1
+    || err "Error: awk not found in PATH.  It must be installed to run this script."
 
-        # The name and location of the files that will be used to get Linux
-        # release info
-        osRelease="/etc/os-release"
+    id -u \
+    | xargs test 0 -ne \
+    && err "This script requires root privileges to run."
 
-        os="" # Will be "linux" or "freebsd"
-        osName="" # Will be "ubuntu", "debian", "rhel",
-                  # "centos", "suse", "amzn", or "freebsd"
-        osVersion=""
+    echo "This script will setup repositories for NGINX Unit"
 
-        id -u \
-        | xargs test 0 -ne \
-        && err "This script requires root privileges to run."
+    osNameVersion=$(getOS)
+    os=$(echo "$osNameVersion" | awk -F: '{print $1}')
+    osName=$(echo "$osNameVersion" | awk -F: '{print $2}')
+    osVersion=$(echo "$osNameVersion" | awk -F: '{print $3}')
 
-        echo "This script will setup repositories for NGINX Unit"
+    # Call the appropriate installation function
+    case "$osName" in
+    debian)
+        installDebian
+        ;;
+    ubuntu)
+        installUbuntu
+        ;;
+    rhel)
+        installRedHat
+        ;;
+    centos)
+        installRedHat
+        ;;
+    ol)
+        installRedHat
+        ;;
+    amzn)
+        installAmazon
+        ;;
+    fedora)
+        installFedora
+        ;;
+    *)
+        err "$osName is not supported"
+        ;;
+    esac
 
-        osNameVersion=$(getOS)
-        os=$(echo "$osNameVersion" | awk -F: '{print $1}')
-        osName=$(echo "$osNameVersion" | awk -F: '{print $2}')
-        osVersion=$(echo "$osNameVersion" | awk -F: '{print $3}')
-
-        # Call the appropriate installation function
-        case "$osName" in
-        debian)
-            installDebian
-            ;;
-        ubuntu)
-            installUbuntu
-            ;;
-        rhel)
-            installRedHat
-            ;;
-        centos)
-            installRedHat
-            ;;
-        ol)
-            installRedHat
-            ;;
-        amzn)
-            installAmazon
-            ;;
-        fedora)
-            installFedora
-            ;;
-        *)
-            err "$osName is not supported"
-            ;;
-        esac
-
-        echo
-        echo "All done - NGINX Unit repositories for "$osName" "$osVersion" are set up"
-        echo "Further steps: https://unit.nginx.org/installation/#official-packages"
-    }
-
-    main
-
-    exit 0
+    echo
+    echo "All done - NGINX Unit repositories for "$osName" "$osVersion" are set up"
+    echo "Further steps: https://unit.nginx.org/installation/#official-packages"
 }
 
 
