Use single quotes as much as possible
Reported-by: Artem Konev <a.konev@f5.com>
Signed-off-by: Alejandro Colomar <alx@nginx.com>

diff --git a/bin/setup-unit b/bin/setup-unit
--- a/bin/setup-unit
+++ b/bin/setup-unit
@@ -115,18 +115,18 @@ repo_config()
     {
         os=$(uname | tr '[:upper:]' '[:lower:]')
 
-        if [ "$os" != "linux" ] && [ "$os" != "freebsd" ]; then
+        if [ "$os" != 'linux' ] && [ "$os" != 'freebsd' ]; then
             warn "Error: The OS isn't Linux or FreeBSD, can't proceed."
             err  "On macOS, try 'brew install nginx/unit/unit'."
         fi
 
-        if [ "$os" = "linux" ]; then
-            osRelease="/etc/os-release";
+        if [ "$os" = 'linux' ]; then
+            osRelease='/etc/os-release';
 
             if [ -f "$osRelease" ]; then
                 # The value for the ID and VERSION_ID may or may not be in quotes
                 osName=$( grep "^ID=" "$osRelease" | sed s/\"//g | awk -F= '{ print $2 }')
-                osVersion=$(grep "^VERSION_ID=" "$osRelease" | sed s/\"//g | awk -F= '{ print $2 }')
+                osVersion=$(grep '^VERSION_ID=' "$osRelease" | sed s/\"//g | awk -F= '{ print $2 }')
             else
                 # rhel or centos 6.*
                 if rpm -q redhat-release-server >/dev/null 2>&1; then
@@ -143,7 +143,7 @@ repo_config()
             osName=$os
             osVersion=$(uname -rs | awk -F '[ -]' '{print $2}')
             if [ -z "$osVersion" ]; then
-                err "Unable to get the FreeBSD version"
+                err 'Unable to get the FreeBSD version'
             fi
         fi
 
@@ -189,13 +189,13 @@ repo_config()
 
         case "$osVersion" in
             6|6.*|7|7.*|8|8.*)
-                dry_run_eval "cat << __EOF__ > /etc/yum.repos.d/unit.repo
+                dry_run_eval 'cat << __EOF__ > /etc/yum.repos.d/unit.repo
 [unit]
 name=unit repo
-baseurl=https://packages.nginx.org/unit/rhel/\$releasever/\$basearch/
+baseurl=https://packages.nginx.org/unit/rhel/$releasever/$basearch/
 gpgcheck=0
 enabled=1
-__EOF__";
+__EOF__';
                 ;;
             *)
                 echo "Unsupported $osName version: $osVersion"
@@ -214,22 +214,22 @@ __EOF__";
 
         case "$osVersion" in
             2)
-                dry_run_eval "cat << __EOF__ > /etc/yum.repos.d/unit.repo
+                dry_run_eval 'cat << __EOF__ > /etc/yum.repos.d/unit.repo
 [unit]
 name=unit repo
-baseurl=https://packages.nginx.org/unit/amzn2/\$releasever/\$basearch/
+baseurl=https://packages.nginx.org/unit/amzn2/$releasever/$basearch/
 gpgcheck=0
 enabled=1
-__EOF__";
+__EOF__';
              ;;
             *)
-                dry_run_eval "cat << __EOF__ > /etc/yum.repos.d/unit.repo
+                dry_run_eval 'cat << __EOF__ > /etc/yum.repos.d/unit.repo
 [unit]
 name=unit repo
-baseurl=https://packages.nginx.org/unit/amzn/\$releasever/\$basearch/
+baseurl=https://packages.nginx.org/unit/amzn/$releasever/$basearch/
 gpgcheck=0
 enabled=1
-__EOF__";
+__EOF__';
              ;;
         esac
 
@@ -242,13 +242,13 @@ __EOF__";
         dry_run_echo 'Install on Fedora';
         dry_run_echo;
 
-        dry_run_eval "cat << __EOF__ > /etc/yum.repos.d/unit.repo
+        dry_run_eval 'cat << __EOF__ > /etc/yum.repos.d/unit.repo
 [unit]
 name=unit repo
-baseurl=https://packages.nginx.org/unit/fedora/\$releasever/\$basearch/
+baseurl=https://packages.nginx.org/unit/fedora/$releasever/$basearch/
 gpgcheck=0
 enabled=1
-__EOF__";
+__EOF__';
 
         dry_run_echo;
         dry_run_eval 'dnf makecache;';
@@ -284,13 +284,13 @@ __EOF__";
     done;
 
     command -v curl >/dev/null \
-    || err "Error: curl not found in PATH.  It must be installed to run this script."
+    || err 'Error: curl not found in PATH.  It must be installed to run this script.';
 
     id -u \
     | xargs test 0 -ne \
-    && err "This script requires root privileges to run."
+    && err 'This script requires root privileges to run.';
 
-    echo "This script sets up the NGINX Unit repository"
+    echo 'This script sets up the NGINX Unit repository';
 
     osNameVersion=$(getOS)
     os=$(echo "$osNameVersion" | awk -F: '{print $1}')
@@ -327,7 +327,7 @@ __EOF__";
 
     echo
     echo "All done; the NGINX Unit repository for "$osName" "$osVersion" is set up."
-    echo "Further steps: https://unit.nginx.org/installation/#official-packages"
+    echo 'Further steps: https://unit.nginx.org/installation/#official-packages'
 }
 
 
@@ -746,12 +746,12 @@ unit_ctl_welcome()
 
     id -u \
     | xargs test 0 -ne \
-    && err "This script requires root privileges to run."
+    && err 'This script requires root privileges to run.';
 
     command -v curl >/dev/null \
-    || err "Error: curl not found in PATH.  It must be installed to run this script."
+    || err 'Error: curl not found in PATH.  It must be installed to run this script.';
 
-    www="/srv/www/unit/index.html";
+    www='/srv/www/unit/index.html';
     test -e "$www" \
     && www="$(mktemp)";
 
@@ -815,13 +815,13 @@ __EOF__";
 
     dry_run_echo;
 
-    echo
-    echo "You may want to try the following commands now:"
-    echo
-    echo "Check out current unitd configuration:"
-    echo "    curl $curl_opt"
-    echo
-    echo "Browse the welcome page:"
+    echo;
+    echo 'You may want to try the following commands now:';
+    echo;
+    echo 'Check out current unitd configuration:';
+    echo "    curl $curl_opt";
+    echo;
+    echo 'Browse the welcome page:';
     echo "    curl http://localhost:$port";
 }
 
@@ -905,7 +905,7 @@ unit_cmd()
     && err "NGINX Unit isn't running.";
 
     test 1 -ne "$nprocs" \
-    && err "Only one NGINX Unit instance should be running.";
+    && err 'Only one NGINX Unit instance should be running.';
 
     unit_ps -t m \
     | sed 's/.*\[\(.*\)].*/\1/';
